import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { describe, expect, it } from 'vitest';

import { collapseToMoves } from '@/api/planStore';

/**
 * The client row shape must match the entity Rayfin provisions — PLAN §13.7.
 *
 * ⚠️ `src/api/planStore.ts` deliberately re-declares the row instead of importing
 * `rayfin/data/PlanChange.ts`, because that file is compiled with TC39 decorators under its own
 * tsconfig and pulling it into the app build drags the schema toolchain into the browser bundle.
 * Duplication without a guard is how a column gets added on one side only — and the failure would
 * be a runtime GraphQL error on a planner's confirm click, not a build error here.
 *
 * So the two are compared by reading the source of both. This is a text comparison rather than a
 * type-level one, which is the point: the type checker cannot see across that boundary at all.
 */

const read = (rel: string) => readFileSync(resolve(process.cwd(), rel), 'utf-8');

/**
 * ⚠️ `.env.local` IS GENERATED BY `rayfin env` AND GITIGNORED, so a fresh clone does not have it.
 * The case below compares the variable NAMES Rayfin emits against the names `planStore.ts` asks
 * for, which cannot be done without the artefact — and on a clean checkout it failed with ENOENT,
 * which reads as a broken template rather than as a missing prerequisite.
 *
 * ⚠️ THE GUARD IS ON CONTENT, NOT ON THE FILE EXISTING. `prebuild` runs `rayfin env`, which can
 * leave a file containing nothing but its own comment header — so an existence check passes on
 * the second run of a suite that skipped on the first, and the test then fails for having no
 * variables rather than for a defect. Asking whether anything was actually emitted is the
 * question that matches what the test needs.
 *
 * The threshold here is ONE, deliberately: the `> 4` assertion inside the test is the real check
 * and must stay able to fail. A guard that demanded five would make it unfailable.
 */
const ENV_LOCAL = (() => {
  const path = resolve(process.cwd(), '.env.local');
  if (!existsSync(path)) return false;
  return /^VITE_[A-Z0-9_]+=/m.test(readFileSync(path, 'utf-8'));
})();

/** Field names from the entity: every `@decorator() name!: type` / `name?: type` line. */
function entityFields(source: string): string[] {
  const names: string[] = [];
  for (const line of source.split('\n')) {
    // Decorators and the property can share a line: `@text({ max: 16 }) site!: string;`
    const match = /@\w+\([^)]*\)\s*(\w+)[!?]:/.exec(line);
    if (match) names.push(match[1]);
  }
  return names.sort();
}

/** Field names from the client interface body. */
function interfaceFields(source: string, name: string): string[] {
  const start = source.indexOf(`export interface ${name} {`);
  expect(start, `interface ${name} not found`).toBeGreaterThan(-1);
  const body = source.slice(start, source.indexOf('\n}', start));
  const names: string[] = [];
  for (const line of body.split('\n').slice(1)) {
    const match = /^\s{2}(\w+)\??:/.exec(line);
    if (match) names.push(match[1]);
  }
  return names.sort();
}

describe('the plan change store', () => {
  it('declares exactly the columns the Fabric entity has', () => {
    const entity = entityFields(read('rayfin/data/PlanChange.ts'));
    const client = interfaceFields(read('src/api/planStore.ts'), 'PlanChangeRow');

    // `id` is generated by the data layer, so the client never sends it — it is added back on the
    // read type. Everything else must line up in both directions.
    expect(entity.length, 'the entity parser found nothing — has the file format changed?')
      .toBeGreaterThan(5);
    expect(client).toEqual(entity.filter((f) => f !== 'id'));
  });

  it('registers the entity in the schema Rayfin provisions from', () => {
    // An entity nobody registers is a table that never exists, and the write fails at runtime with
    // an unknown-type error rather than at deploy time.
    const schema = read('rayfin/data/schema.ts');
    expect(schema).toContain('PlanChange');
    expect(schema).toMatch(/import\s*\{\s*PlanChange\s*\}/);
  });

  it('declares exactly the columns the availability entity has', () => {
    // Same guard, same reason, third table. `TeacherAvailability` records what the plan is JUDGED
    // AGAINST rather than what it is, and it is written from two places (a click and a
    // spreadsheet import) — so a column that exists on one side only would fail at runtime on
    // somebody's upload rather than here.
    const entity = entityFields(read('rayfin/data/TeacherAvailability.ts'));
    const client = interfaceFields(read('src/api/planStore.ts'), 'TeacherAvailabilityRow');

    expect(entity.length, 'the entity parser found nothing — has the file format changed?')
      .toBeGreaterThan(5);
    // `id` IS on the client type here (unlike PlanChangeRow): the id is derived from
    // site+teacher+slot rather than generated, so the client computes it and sends it.
    expect(client).toEqual(entity);
  });

  it('registers the availability entity too', () => {
    const schema = read('rayfin/data/schema.ts');
    expect(schema).toMatch(/import\s*\{\s*TeacherAvailability\s*\}/);
    expect(schema).toMatch(/TeacherAvailability:\s*typeof\s+TeacherAvailability/);
  });

  it.skipIf(!ENV_LOCAL)(
    'reads the Fabric identifiers under the names Rayfin actually emits (needs `rayfin env --framework vite`)',
    () => {
    // ⚠️ THIS IS THE TEST THAT WOULD HAVE SAVED THE FEATURE. `planStore.ts` originally asked for
    // `VITE_WORKSPACE_ID` / `VITE_RAYFIN_WORKSPACE_ID`, by analogy with the scheduler variables.
    // `rayfin env` emits `VITE_FABRIC_WORKSPACE_ID`. Both lookups returned '', so signing in was
    // impossible, the button that offers it never rendered, and the durable store could never
    // receive a row — silently, because the honest "not saved" message looked like the expected
    // state rather than like a defect.
    //
    // Checking the BUNDLE for the workspace UUID did not catch it: the value is inlined from
    // .env.local under its real name, so it is present in the artefact no matter which key this
    // file reads. Only the NAMES can be compared, so the names are what this asserts.
    const envFile = read('.env.local');
    const emitted = [...envFile.matchAll(/^(VITE_[A-Z0-9_]+)=/gm)].map((m) => m[1]);
    expect(emitted.length, '.env.local looks empty — run `rayfin env --framework vite`')
      .toBeGreaterThan(4);

    const store = read('src/api/planStore.ts');
    const asked = new Set([...store.matchAll(/'(VITE_[A-Z0-9_]+)'/g)].map((m) => m[1]));

    // Every Fabric identifier the store needs must be asked for under a name that is really there.
    for (const needed of emitted.filter((n) => n.startsWith('VITE_FABRIC_'))) {
      if (needed === 'VITE_FABRIC_TENANT_ID') continue; // not used by the store
      expect(asked, `planStore.ts never reads ${needed}`).toContain(needed);
    }
    },
  );
});

describe('collapsing the change log into a plan', () => {
  const row = (sessionId: string, toSlotId: string, roomId: string) => ({ sessionId, toSlotId, roomId });

  it('keeps only the newest decision for a session', () => {
    // `listPlanChanges` orders newest FIRST. A session moved twice must end where it was put last.
    const moves = collapseToMoves([
      row('S1', 'Mi-6', 'i 107'), // newest
      row('S1', 'Mo-1', 'D 216'), // superseded
    ]);
    expect(moves).toEqual([{ sessionId: 'S1', slotId: 'Mi-6', roomId: 'i 107' }]);
  });

  it('keeps one entry per session, not one per save', () => {
    const moves = collapseToMoves([row('S1', 'Mi-6', 'i 107'), row('S2', 'Do-6', 'A 449'), row('S1', 'Mo-1', 'D 216')]);
    expect(moves).toHaveLength(2);
    expect(moves.map((m) => m.sessionId).sort()).toEqual(['S1', 'S2']);
  });

  it('is empty for an empty log, rather than inventing a baseline move', () => {
    expect(collapseToMoves([])).toEqual([]);
  });

  it('would fail if the reversal were dropped', () => {
    // The mirror of the first case: reading the log as given lets the OLDEST write win. Asserting
    // the wrong answer is absent is what makes the first test meaningful rather than incidental.
    const moves = collapseToMoves([row('S1', 'Mi-6', 'i 107'), row('S1', 'Mo-1', 'D 216')]);
    expect(moves[0].slotId).not.toBe('Mo-1');
  });

  it('deleting a change means deleting EVERY row for that session', () => {
    /*
     * ⚠️ THIS IS WHY `deletePlanChanges` FILTERS BY SESSION AND NOT BY THE ROW ON SCREEN. The
     * Änderungen list shows one line per session — the collapsed, newest decision. Deleting the
     * row behind that line and stopping there leaves the EARLIER row in the log, and the next
     * collapse promotes it. The change does not disappear; it silently becomes a DIFFERENT change,
     * still listed, now pointing somewhere nobody chose. That is worse than the bug the delete
     * exists to fix, because the list did visibly react and looks like it worked.
     *
     * Asserted on `collapseToMoves` rather than through the data layer because the hazard is in
     * the collapse, and this is the same reason the function is exported at all.
     */
    const log = [row('S1', 'Mi-6', 'i 107'), row('S1', 'Mo-1', 'D 216')];

    const newestOnly = collapseToMoves(log.slice(1)); // the wrong fix: drop just the visible row
    expect(newestOnly).toHaveLength(1);
    expect(newestOnly[0].slotId).toBe('Mo-1'); // resurfaced, and still on screen

    const wholeSession = collapseToMoves(log.filter((r) => r.sessionId !== 'S1'));
    expect(wholeSession).toEqual([]); // actually gone
  });
});

describe('collapsing the change log into a plan', () => {
  const row = (sessionId: string, toSlotId: string, roomId: string) => ({ sessionId, toSlotId, roomId });

  it('keeps only the newest decision for a session', () => {
    // `listPlanChanges` orders newest FIRST, so a session moved twice must end where it was put
    // last. Getting this backwards resurrects a move somebody had already replaced.
    const moves = collapseToMoves([
      row('S1', 'Mi-6', 'i 107'),
      row('S1', 'Mo-1', 'D 216'),
    ]);
    expect(moves).toEqual([{ sessionId: 'S1', slotId: 'Mi-6', roomId: 'i 107' }]);
  });

  it('reports one entry per session, not one per save', () => {
    const moves = collapseToMoves([
      row('S1', 'Mi-6', 'i 107'),
      row('S2', 'Do-6', 'A 449'),
      row('S1', 'Mo-1', 'D 216'),
    ]);
    expect(moves).toHaveLength(2);
    expect(moves.map((m) => m.sessionId).sort()).toEqual(['S1', 'S2']);
  });

  it('is empty for an empty log, rather than inventing a move', () => {
    expect(collapseToMoves([])).toEqual([]);
  });

  it('does not let the oldest write win', () => {
    // The mirror of the first case. Asserting the WRONG answer is absent is what makes the first
    // test meaningful rather than something that would pass either way.
    const moves = collapseToMoves([row('S1', 'Mi-6', 'i 107'), row('S1', 'Mo-1', 'D 216')]);
    expect(moves[0].slotId).not.toBe('Mo-1');
  });
});

/**
 * The `site` key must be the SCHEDULER SITE, on both sides of every write.
 *
 * ⚠️ THIS SHIPPED BROKEN AND LOOKED PERFECT. `CalendarPanel` wrote its rows with `site: aoiId`
 * ('oth-regensburg') while `currentPlanMoves` reads with `schedulerSite` ('oth') and
 * `tools/fabric/seed_plan_assignments.py` seeds with it. Nothing errored: the rows were accepted,
 * the confirm reported success, and the moves were then invisible to every reader — a confirmed
 * change silently vanished on reload. Measured on the live store: 5 rows under 'oth-regensburg',
 * 0 findable by the app.
 *
 * Worse for the assignments half. `assignmentId` hashes site+sessionId, so the wrong key produced a
 * DIFFERENT id from the baseline row for the same session: the upsert inserted a duplicate rather
 * than moving the session, which is the exact opposite of what that write exists to do.
 *
 * A type checker cannot see this — both are `string`. So it is guarded as a source shape, the same
 * technique this file already uses for the entity columns above.
 */
describe('the site key on plan writes', () => {
  const panel = read('src/components/CalendarPanel.tsx');

  it('never writes a plan row keyed by the AOI id', () => {
    const offending = panel
      .split('\n')
      .map((line, i) => ({ line: line.trim(), n: i + 1 }))
      .filter(({ line }) => /^site:\s*aoiId\b/.test(line));
    expect(
      offending,
      `CalendarPanel writes site: aoiId at line(s) ${offending.map((o) => o.n).join(', ')} — ` +
        'plan rows must be keyed by schedulerSite, or nothing will ever read them back'
    ).toEqual([]);
  });

  it('writes every plan row keyed by the scheduler site', () => {
    const keys = [...panel.matchAll(/^\s*site:\s*(\w+)/gm)].map((m) => m[1]);
    // Guard against a vacuous pass: if the writes are ever renamed away, this test must not keep
    // reporting success over a file that no longer contains them.
    expect(keys.length, 'no plan-row site keys found — has the write moved?').toBeGreaterThan(0);
    expect(new Set(keys)).toEqual(new Set(['aoiSchedulerSite']));
  });

  it('the two identifiers really are different strings, which is why this can go wrong', () => {
    // If these ever became equal the bug would be unreachable and this guard could be dropped.
    const aoi = JSON.parse(read('config/aoi/oth-regensburg.json')) as {
      id: string;
      schedulerSite?: string;
    };
    expect(aoi.schedulerSite).toBeDefined();
    expect(aoi.schedulerSite).not.toBe(aoi.id);
  });
});
