import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { describe, expect, it } from 'vitest';

import buildings from '@config/buildings-oth.json';
import planRooms from '@config/rooms-plan.json';

/**
 * The generated dataset, read at RUNTIME rather than imported.
 *
 * ⚠️ `/data/` IS GITIGNORED, SO A FRESH CLONE DOES NOT HAVE IT. These three used to be static
 * `import ... from '../../../data/synthetic/*.json'`, which Vite resolves at collection time — so
 * on a clean checkout the whole suite failed to LOAD, not to assert. `git clone && npm i && npm
 * test` is the first thing anyone does with a template, and it was red for a reason that is not a
 * defect: the data is rebuilt by `npm run data:build` and the generators, and shipping 1.5 GB of
 * it is not an option.
 *
 * `process.cwd()` rather than `import.meta.url`: under Vitest the latter is an http URL and
 * `fileURLToPath` refuses it — recorded once already in this repo.
 */
const generated = (rel: string): unknown | null => {
  const path = resolve(process.cwd(), rel);
  return existsSync(path) ? (JSON.parse(readFileSync(path, 'utf-8')) as unknown) : null;
};

const synthetic = generated('data/synthetic/room.json');
const syntheticBuildings = generated('data/synthetic/building.json');
const planRoomRefused = generated('data/synthetic/plan_room_refused.json');

/**
 * ⚠️ SKIPPED WITH A REASON, NEVER PASSED VACUOUSLY. The two cases below are the ones that join
 * the extracted plans to the dataset, and they are the strongest checks in the file. Letting them
 * quietly succeed against an absent dataset would be worse than not having them, so they skip,
 * the reporter says so, and the reason names the command that makes them run.
 */
const DATASET = synthetic !== null && syntheticBuildings !== null && planRoomRefused !== null;
const NEEDS_DATASET = 'run `python tools/data/generate_timetable.py --site oth` first';

/**
 * The rooms read off OTH's published floor plans — PLAN §5.4.
 *
 * ⚠️ THIS FILE IS GENERATED BY AN IMAGE PIPELINE, WHICH IS WHY IT IS TESTED AS DATA.
 * `tools/data/build_plan_rooms.py` renders each sheet, reads the labels back with OCR, carves the
 * rooms out between the drawn walls and georeferences them. Every stage has a quiet failure mode
 * that produces confident, wrong geometry, and several of them did:
 *
 *   - a wall threshold that missed the 147-grey wall fill fused all 24 rooms into one region;
 *   - watershed run on the rendered page stopped at the furniture, every room ~half size;
 *   - seeding rooms but not the foyer let K 033 take the corridor — 1260 m², forty times over;
 *   - the reflection was chosen by assumption once, putting the two wings the wrong way round;
 *   - "centring" the floor on the footprint using vertex means instead of area centroids moved
 *     the whole building 15.85 m.
 *
 * Each of those passed a casual look at the numbers. What catches them is checking the geometry
 * against something independently surveyed, which is what these tests do.
 */

interface PlanRoom {
  ref: string;
  building: string;
  level: number;
  areaM2: number;
  polygonUtm32: number[][];
}

const rooms = planRooms.rooms as PlanRoom[];

// Both config files wrap their array in a key; the synthetic dataset is a bare array. Unwrapping
// defensively keeps this test about the geometry rather than about file shapes.
const unwrap = <T,>(value: unknown, key: string): T[] =>
  Array.isArray(value) ? (value as T[]) : ((value as Record<string, T[]>)[key] ?? []);

interface Surveyed {
  ref?: string | null;
  campusId?: string;
  polygonUtm32?: number[][];
  isUniversityBuilding?: boolean;
  othEvidence?: unknown;
}

const surveyed = unwrap<Surveyed>(buildings, 'buildings');

/**
 * What each published building is checked AGAINST — mirrors `TARGETS` in build_plan_rooms.py.
 *
 * ⚠️ ONE PUBLISHED BUILDING IS NOT ONE SURVEYED POLYGON. Gebäude K is a single OpenStreetMap
 * relation carrying `ref=K`, so it has exactly one ring. OTH publishes the whole Prüfening campus
 * as one plan numbered `P …`, and OpenStreetMap has that campus as fourteen separate polygons with
 * no ref at all — so its target is the SET of them. An earlier version of this file checked every
 * room against K's ring, which is why adding a second building reported 57 rooms "outside the
 * footprint": they were outside K, four kilometres away, exactly as they should be.
 *
 * ⚠️ AND IT IS THE UNIVERSITY'S POLYGONS, NOT EVERYTHING ON THE CAMPUS. `campusId` is a location,
 * so it also returns the industrial halls and housing that share the Prüfening block — 303 polygons
 * and 119 482 m² against the university's 14 and 7 500. Divided by the larger figure the published
 * floor covers 4% of "its" footprint and the coverage check fails on a floor that is fine. The
 * extractor filters on the same two flags; both sides have to ask the same question.
 */
const pruefening = surveyed.filter(
  (b) =>
    b.campusId === 'pruefening' &&
    b.polygonUtm32 &&
    (b.othEvidence || b.isUniversityBuilding)
);

const TARGETS: Record<string, number[][][]> = {
  K: surveyed.filter((b) => b.ref === 'K').map((b) => b.polygonUtm32 as number[][]),
  P: pruefening.map((b) => b.polygonUtm32 as number[][]),
};

/**
 * How far a room may reach past its target, in metres.
 *
 * A single surveyed polygon is a wall away from the truth, so a metre. A SET of polygons is not,
 * and the reason is worth stating because the number looks slack: the extractor fits to the OUTER
 * HULL of the merged polygons, which swallows the courtyards and the gaps between separately
 * mapped wings. OpenStreetMap's Prüfening mapping is known to be partial — the AOI config records
 * it, and OTH's own site plan shows a larger L-shaped complex — so a room in an unmapped wing sits
 * outside every individual ring while being inside the building. Measured, the worst is 7.6 m. Ten
 * metres therefore still catches the failure this test exists for: the rooms it caught before sat
 * 20 to 55 m out.
 */
const tolerance = (building: string) => (TARGETS[building].length > 1 ? 10 : 1);

const areaOf = (poly: number[][]) =>
  Math.abs(
    poly.reduce((sum, [x, y], i) => {
      const [px, py] = poly[(i + 1) % poly.length];
      return sum + (x * py - px * y);
    }, 0) / 2
  );

const inside = (x: number, y: number, poly: number[][]) => {
  let hit = false;
  for (let i = 0; i < poly.length; i += 1) {
    const [x1, y1] = poly[i];
    const [x2, y2] = poly[(i + 1) % poly.length];
    if (y1 > y !== y2 > y && x < ((x2 - x1) * (y - y1)) / (y2 - y1) + x1) hit = !hit;
  }
  return hit;
};

/** Shortest distance from a point to a ring, so "outside" can be measured rather than just flagged. */
const distanceTo = (x: number, y: number, poly: number[][]) => {
  let best = Infinity;
  for (let i = 0; i < poly.length; i += 1) {
    const [ax, ay] = poly[i];
    const [bx, by] = poly[(i + 1) % poly.length];
    const dx = bx - ax;
    const dy = by - ay;
    const span = dx * dx + dy * dy;
    const t = span === 0 ? 0 : Math.max(0, Math.min(1, ((x - ax) * dx + (y - ay) * dy) / span));
    best = Math.min(best, Math.hypot(x - (ax + t * dx), y - (ay + t * dy)));
  }
  return best;
};

/** Does the ring avoid crossing itself? */
const simple = (poly: number[][]) => {
  const side = (a: number[], b: number[], c: number[]) =>
    Math.sign((b[0] - a[0]) * (c[1] - a[1]) - (b[1] - a[1]) * (c[0] - a[0]));
  const n = poly.length;
  for (let i = 0; i < n; i += 1) {
    for (let j = i + 2; j < n; j += 1) {
      if (i === 0 && j === n - 1) continue;
      const [p, p2, q, q2] = [poly[i], poly[(i + 1) % n], poly[j], poly[(j + 1) % n]];
      if (side(p, p2, q) !== side(p, p2, q2) && side(q, q2, p) !== side(q, q2, p2)) return false;
    }
  }
  return true;
};

describe('rooms read from OTH floor plans', () => {
  it('covers the buildings whose plans OTH publishes', () => {
    expect(rooms.length).toBeGreaterThanOrEqual(60);
    expect(new Set(rooms.map((r) => r.building))).toEqual(new Set(Object.keys(TARGETS)));
    expect(new Set(rooms.map((r) => r.level))).toEqual(new Set([0, 1]));
  });

  it('places every room inside the surveyed building footprint', () => {
    // ⚠️ VERTICES, not centroids. "Is the centroid inside" sounds equivalent and is not: the area
    // centroid and the vertex mean disagreed on 14 of these rooms, because a traced ring can carry
    // a hairline spur that skews one and not the other. Vertices are unambiguous, they are what
    // the 3D view actually draws, and this is the stricter question.
    //
    // A room passes on ONE ring, not on all of them — for a campus target the rings are separate
    // buildings and no room can be in two.
    const strays = rooms
      .map((room) => {
        const limit = tolerance(room.building);
        const rings = TARGETS[room.building];
        const out = room.polygonUtm32.filter((point) =>
          rings.every(
            (ring) =>
              !inside(point[0], point[1], ring) && distanceTo(point[0], point[1], ring) > limit
          )
        );
        return { ref: room.ref, out };
      })
      .filter((r) => r.out.length > 0);
    expect(strays.map((s) => s.ref)).toEqual([]);
  });

  it('traces rings that do not cross themselves', () => {
    // A folded ring still yields a plausible area — that is exactly how the first version of this
    // file passed while carrying rooms whose centroid sat 13 m outside their own bounding box.
    // Crossing is the property that was actually violated, so it is the property to assert.
    const folded = rooms.filter((room) => !simple(room.polygonUtm32));
    expect(folded.map((r) => r.ref)).toEqual([]);
  });

  it('fills a believable share of each floor and no more', () => {
    // Rooms cannot cover the whole footprint — corridors, stairs, WCs and two courtyards are not
    // rooms — but they cannot be a rounding error either. Leaking regions blow straight past this.
    //
    // ⚠️ EACH BUILDING IS MEASURED AGAINST ITS OWN FOOTPRINT. Summing every published room and
    // dividing by Gebäude K's area gave 1.41 the moment a second building appeared — a number that
    // says nothing about either of them. The lower bound is per building for the same reason: K's
    // sheets number every room on the floor, while the Prüfening sheet is one drawing of six
    // surveyed polygons and only the rooms OTH labelled come back, so a smaller share of that
    // footprint is the honest answer rather than a failure.
    const floors = new Set(rooms.map((r) => `${r.building}|${r.level}`));
    expect(floors.size).toBeGreaterThanOrEqual(3);
    for (const floor of floors) {
      const [building, level] = floor.split('|');
      const footprint = TARGETS[building].reduce((sum, ring) => sum + areaOf(ring), 0);
      const total = rooms
        .filter((r) => r.building === building && String(r.level) === level)
        .reduce((sum, r) => sum + areaOf(r.polygonUtm32), 0);
      expect({ floor, share: total / footprint > 0.08 }).toEqual({ floor, share: true });
      expect({ floor, share: total / footprint < 0.75 }).toEqual({ floor, share: true });
    }
  });

  it('states an area that matches the ring it stores', () => {
    // ⚠️ WEAK ON ITS OWN, and kept only alongside the crossing test above: both numbers come from
    // the same shoelace over the same ring, so this agrees perfectly even when the ring is folded.
    // It catches a ring and an area drifting apart in the file, nothing more.
    for (const room of rooms) {
      expect(Math.abs(areaOf(room.polygonUtm32) - room.areaM2)).toBeLessThan(1);
    }
  });

  it.skipIf(!DATASET)(`names rooms the timetable actually knows (${NEEDS_DATASET})`, () => {
    // Geometry that does not join to a room in the dataset is decoration: it can never be
    // coloured by its bookings, which is the entire point of drawing it.
    //
    // ⚠️ THE BUILDING ON THE DOOR IS NOT ALWAYS THE BUILDING IN THE DATASET. OTH numbers the whole
    // Prüfening complex `P …` and OpenStreetMap has it as six separate polygons with no ref, so the
    // generator files each room under the polygon that contains it and records the published letter
    // in `planBuilding`. Joining on the published letter alone reported all 57 of those rooms as
    // orphans while every one of them was in the dataset — the test would have been asking for a
    // building this project deliberately does not invent.
    //
    // ⚠️ A REFUSAL IS NOT AN ORPHAN, BUT IT HAS TO BE DECLARED. Because that filing is a GUESS, the
    // generator now checks it: four Prüfening floors were handed more room area than the polygon
    // they were filed under can physically hold (building `f`: 442 m² of rooms in a 353 m²
    // footprint) and are dropped, which is why those buildings show generated squares instead.
    // Allowing them here silently would let this contract rot into "anything may be missing", so
    // the generator writes `plan_room_refused.json` and the room must appear in ONE of the two
    // lists — used, or refused with a reason.
    const known = new Set(
      unwrap<{ roomId: string; buildingId: string; level: number; planBuilding?: string | null }>(
        synthetic,
        'rooms'
      ).map((r) => `${r.roomId}|${r.planBuilding ?? r.buildingId}|${r.level}`)
    );
    const refused = new Set(
      unwrap<{ ref: string; publishedBuilding: string; level: number }>(
        planRoomRefused,
        'rooms'
      ).map((r) => `${r.ref}|${r.publishedBuilding}|${r.level}`)
    );
    const orphans = rooms.filter(
      (r) => !known.has(`${r.ref}|${r.building}|${r.level}`) &&
        !refused.has(`${r.ref}|${r.building}|${r.level}`)
    );
    expect(orphans.map((r) => r.ref)).toEqual([]);
  });

  it.skipIf(!DATASET)(
    `never files more room onto a floor than the building has ground (${NEEDS_DATASET})`,
    () => {
    // ⚠️ THIS IS THE CHECK NOBODY WAS DOING, AND IT IS WHY PRÜFENING LOOKED WRONG. The extractor
    // georeferences a SHEET to ONE building and validates every room vertex against THAT footprint.
    // OTH numbers the whole Prüfening complex `P …` while OpenStreetMap maps it as six partial
    // polygons, so which polygon owns a room is decided by containment — a guess — and nothing
    // downstream asked whether the polygon was big enough. Building `f` was handed 442 m² of rooms
    // into a 353 m² footprint: 125 %, which is not a bad estimate but a physical impossibility.
    //
    // The ceiling is read off the floors this project can MEASURE: Seyboth's K, anchored on 24
    // surveyed rooms, comes out at 39.3 % and 33.7 %, and OTH's published floors run 23–40 % once
    // corridors, stairs, walls and WCs are taken out. 60 % clears every honest floor with room to
    // spare and catches every broken one; nothing in the dataset sits near the line.
    //
    // ⚠️ IT IS DELIBERATELY NOT A CLAIM ABOUT BUILDINGS IN GENERAL. LMU's Oettingenstraße 67 runs
    // at 73–76 % and its fit is the best-evidenced in the project (521 named correspondences, RMS
    // 0.95–1.28 m), so an earlier version of this ceiling applied everywhere threw away all 686 of
    // its rooms. Density is a fact about a building; what is checked here is a floor whose
    // OWNERSHIP WAS GUESSED, where being wrong is possible in the first place.
    const footprint = new Map(
      unwrap<{ buildingId: string; footprintM2: number }>(syntheticBuildings, 'buildings').map(
        (b) => [b.buildingId, b.footprintM2]
      )
    );
    const area = new Map<string, number>();
    for (const r of unwrap<{
      buildingId: string;
      level: number;
      areaM2: number;
      provenance?: string;
    }>(synthetic, 'rooms')) {
      if (r.provenance !== 'plan') continue;
      const key = `${r.buildingId}|${r.level}`;
      area.set(key, (area.get(key) ?? 0) + (r.areaM2 ?? 0));
    }

    const impossible = [...area.entries()]
      .map(([key, sum]) => {
        const [bid] = key.split('|');
        const foot = footprint.get(bid) ?? 0;
        return { key, cover: foot > 0 ? sum / foot : 0 };
      })
      .filter((x) => x.cover > 0.6)
      .map((x) => `${x.key} ${(x.cover * 100).toFixed(0)}%`);

    expect(impossible).toEqual([]);
    },
  );

  it('produces rooms of a plausible size', () => {
    const areas = rooms.map((r) => r.areaM2).sort((a, b) => a - b);
    expect(areas[0]).toBeGreaterThan(4);
    expect(areas[areas.length - 1]).toBeLessThan(400);
  });
});
