/**
 * Coherent, deterministic FP&A fixture for the Financial Statements showcase.
 *
 * GRAIN & INVARIANTS (read before editing):
 * - Facts are monthly. `period` is an ISO `YYYY-MM` key; each maps to a month-end date.
 * - Fiscal year == calendar year (fyStartMonth = 1). Documented so YTD/QTD/FY are unambiguous.
 * - `AS_OF` is the reporting anchor. Months <= AS_OF have Actuals (AC); months after AS_OF
 *   are forecast-only (AC is absent, FC carries the outlook). Budget (BU) exists for all
 *   in-year months (an annual plan). Prior Year (PY) is NOT a scenario — it is derived by
 *   looking up the SAME line's AC exactly 12 months earlier (see statement-model.ts).
 * - Revenue reconciles to the product driver facts: Revenue(period,scenario) ==
 *   Σ products units*price. This keeps the PVM (price/volume/mix) bridge internally
 *   consistent with the P&L.
 * - Cost lines are stored as POSITIVE magnitudes with `sign: -1` in the row model, so a
 *   single rollup can subtotal them; presentation flips the sign. Never store negative here.
 * - Working-capital + capex facts (`wcFacts`) are the explicit, reconciled inputs the
 *   indirect cash-flow statement is built from — cash flow is NOT re-derived from the P&L.
 *
 * Everything is generated by a seeded PRNG so the dataset is byte-stable across builds
 * (no Math.random, no Date.now) — required for deterministic snapshot tests.
 */

export type Scenario = "AC" | "BU" | "FC";

export interface FiscalCalendar {
  /** 1 = January. Calendar-aligned fiscal year for this demo dataset. */
  fyStartMonth: number;
}

export const CALENDAR: FiscalCalendar = { fyStartMonth: 1 };

/** Two full calendar years of monthly periods: 2023-01 .. 2024-12. */
export const START_YEAR = 2023;
export const YEARS = 2;

/** Reporting anchor: Actuals are closed through this month-end. */
export const AS_OF = "2024-08";

export const CURRENCIES = ["USD", "EUR", "GBP"] as const;
export type CurrencyCode = (typeof CURRENCIES)[number];
export const BASE_CURRENCY: CurrencyCode = "USD";

/** All monthly period keys in order, e.g. "2023-01". */
export const PERIODS: string[] = (() => {
  const out: string[] = [];
  for (let y = 0; y < YEARS; y++) {
    for (let m = 1; m <= 12; m++) {
      out.push(`${START_YEAR + y}-${String(m).padStart(2, "0")}`);
    }
  }
  return out;
})();

/** Month-end ISO date for a period key (used for date-based period filtering). */
export function periodEndDate(period: string): string {
  const [y, m] = period.split("-").map(Number);
  const end = new Date(y, m, 0); // day 0 of next month = last day of this month
  return end.toISOString().slice(0, 10);
}

/** True when a period is actualised (<= AS_OF). */
export function isActualPeriod(period: string): boolean {
  return period <= AS_OF;
}

// ── P&L line model ──────────────────────────────────────────────────────────
// Subtotals are COMPUTED by rollup (statement-model.ts), never stored as facts.
// Each row references the leaf ids that sum into it (each leaf carries its own
// sign), so the statement reconciles by construction.

export interface PnlRow {
  id: string;
  label: string;
  /** Leaf ids composing this row; a leaf row references only itself. */
  components: PnlLeafId[];
  kind: "leaf" | "subtotal";
  /** Presentation sign: revenue/subtotals +1, cost lines -1. */
  sign: 1 | -1;
  level: number;
  emphasis?: boolean;
}

/** The P&L leaf ids that carry their own sign (used to sum any subtotal). */
export const PNL_LEAVES = [
  "rev_platform",
  "rev_analytics",
  "rev_services",
  "cogs_cloud",
  "cogs_support",
  "opex_sm",
  "opex_rd",
  "opex_ga",
  "da",
] as const;
export type PnlLeafId = (typeof PNL_LEAVES)[number];

/** Leaf sign lookup, so a rollup can apply the correct sign per component. */
export const LEAF_SIGN: Record<PnlLeafId, 1 | -1> = {
  rev_platform: 1,
  rev_analytics: 1,
  rev_services: 1,
  cogs_cloud: -1,
  cogs_support: -1,
  opex_sm: -1,
  opex_rd: -1,
  opex_ga: -1,
  da: -1,
};

const REV = ["rev_platform", "rev_analytics", "rev_services"] as const;
const COGS = ["cogs_cloud", "cogs_support"] as const;
const OPEX = ["opex_sm", "opex_rd", "opex_ga"] as const;

export const PNL_ROWS: PnlRow[] = [
  { id: "revenue", label: "Revenue", kind: "subtotal", sign: 1, level: 0, emphasis: true, components: [...REV] },
  { id: "rev_platform", label: "Core Platform", kind: "leaf", sign: 1, level: 1, components: ["rev_platform"] },
  { id: "rev_analytics", label: "Analytics Add-on", kind: "leaf", sign: 1, level: 1, components: ["rev_analytics"] },
  { id: "rev_services", label: "Professional Services", kind: "leaf", sign: 1, level: 1, components: ["rev_services"] },
  { id: "cogs", label: "Cost of Revenue", kind: "subtotal", sign: -1, level: 0, components: [...COGS] },
  { id: "cogs_cloud", label: "Cloud & Hosting", kind: "leaf", sign: -1, level: 1, components: ["cogs_cloud"] },
  { id: "cogs_support", label: "Support & Delivery", kind: "leaf", sign: -1, level: 1, components: ["cogs_support"] },
  { id: "gross_profit", label: "Gross Profit", kind: "subtotal", sign: 1, level: 0, emphasis: true, components: [...REV, ...COGS] },
  { id: "opex", label: "Operating Expenses", kind: "subtotal", sign: -1, level: 0, components: [...OPEX] },
  { id: "opex_sm", label: "Sales & Marketing", kind: "leaf", sign: -1, level: 1, components: ["opex_sm"] },
  { id: "opex_rd", label: "Research & Development", kind: "leaf", sign: -1, level: 1, components: ["opex_rd"] },
  { id: "opex_ga", label: "General & Admin", kind: "leaf", sign: -1, level: 1, components: ["opex_ga"] },
  { id: "ebitda", label: "EBITDA", kind: "subtotal", sign: 1, level: 0, emphasis: true, components: [...REV, ...COGS, ...OPEX] },
  { id: "da", label: "Depreciation & Amortization", kind: "leaf", sign: -1, level: 1, components: ["da"] },
  { id: "ebit", label: "Operating Income (EBIT)", kind: "subtotal", sign: 1, level: 0, emphasis: true, components: [...REV, ...COGS, ...OPEX, "da"] },
];

// ── Fact tables ─────────────────────────────────────────────────────────────

/** One stored value for a P&L leaf (magnitude, always >= 0). */
export interface PnlFact {
  period: string;
  scenario: Scenario;
  line: PnlLeafId;
  /** Positive magnitude; sign is applied from LEAF_SIGN at rollup time. */
  value: number;
}

export const PRODUCTS = ["Core Platform", "Analytics Add-on", "Professional Services"] as const;
export type ProductName = (typeof PRODUCTS)[number];
export type RevenueLeafId = Extract<PnlLeafId, "rev_platform" | "rev_analytics" | "rev_services">;

/** Product driver fact — Revenue leaf value == units*price for the matching product. */
export interface ProductFact {
  period: string;
  scenario: Scenario;
  product: ProductName;
  line: RevenueLeafId;
  units: number;
  /** Average selling price per unit, in base currency. */
  price: number;
}

/** Explicit reconciled inputs for the indirect cash-flow statement (Actuals only). */
export interface WorkingCapitalFact {
  period: string;
  /** Closing balances, base currency. */
  ar: number;
  inventory: number;
  ap: number;
  /** Cash capex in the month (outflow, positive magnitude). */
  capex: number;
}

/** FX average rate: units of `currency` per 1 base (USD). */
export interface FxRate {
  period: string;
  currency: CurrencyCode;
  /** Average rate for the period (P&L translation). */
  avgRate: number;
}

// ── Seeded generator ────────────────────────────────────────────────────────

function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const rand = mulberry32(0x5eedface);
const jitter = (pct: number) => 1 + (rand() * 2 - 1) * pct;

/** Monthly seasonality multiplier (softly higher in Q4, dip in spring). */
function seasonality(monthIndex: number): number {
  const m = monthIndex % 12; // 0=Jan
  const wave = Math.sin(((m - 2) / 12) * Math.PI * 2) * 0.06;
  const q4 = m >= 9 ? 0.05 : 0;
  return 1 + wave + q4;
}

/** Compound monthly growth from a baseline across the span. */
function growth(monthIndex: number, monthlyRate: number): number {
  return Math.pow(1 + monthlyRate, monthIndex);
}

interface ProductSpec {
  product: ProductName;
  line: RevenueLeafId;
  baseUnits: number;
  basePrice: number;
  unitGrowth: number;
  priceGrowth: number;
}

const PRODUCT_SPECS: ProductSpec[] = [
  { product: "Core Platform", line: "rev_platform", baseUnits: 4200, basePrice: 1450, unitGrowth: 0.012, priceGrowth: 0.003 },
  { product: "Analytics Add-on", line: "rev_analytics", baseUnits: 2600, basePrice: 720, unitGrowth: 0.02, priceGrowth: 0.0045 },
  { product: "Professional Services", line: "rev_services", baseUnits: 1500, basePrice: 900, unitGrowth: 0.008, priceGrowth: 0.002 },
];

/** Scenario multipliers applied on top of the actual trend line. */
const SCENARIO_UNIT_BIAS: Record<Scenario, number> = { AC: 1, BU: 1.04, FC: 1.01 };
const SCENARIO_PRICE_BIAS: Record<Scenario, number> = { AC: 1, BU: 1.01, FC: 1.005 };

function buildProductFacts(): ProductFact[] {
  const facts: ProductFact[] = [];
  PERIODS.forEach((period, i) => {
    const actual = isActualPeriod(period);
    const scenarios: Scenario[] = actual ? ["AC", "BU", "FC"] : ["BU", "FC"];
    for (const spec of PRODUCT_SPECS) {
      const season = seasonality(i);
      for (const scenario of scenarios) {
        const units = Math.round(
          spec.baseUnits * growth(i, spec.unitGrowth) * season * SCENARIO_UNIT_BIAS[scenario] * (scenario === "AC" ? jitter(0.03) : 1),
        );
        const price = Math.round(spec.basePrice * growth(i, spec.priceGrowth) * SCENARIO_PRICE_BIAS[scenario] * (scenario === "AC" ? jitter(0.01) : 1));
        facts.push({ period, scenario, product: spec.product, line: spec.line, units, price });
      }
    }
  });
  return facts;
}

export const productFacts: ProductFact[] = buildProductFacts();

/** Revenue leaf value for a period/scenario/line = Σ units*price for that product. */
function revenueFor(period: string, scenario: Scenario, line: RevenueLeafId): number {
  return productFacts
    .filter((f) => f.period === period && f.scenario === scenario && f.line === line)
    .reduce((s, f) => s + f.units * f.price, 0);
}

function totalRevenue(period: string, scenario: Scenario): number {
  return PRODUCT_SPECS.reduce((s, spec) => s + revenueFor(period, scenario, spec.line), 0);
}

interface CostSpec {
  line: Exclude<PnlLeafId, RevenueLeafId>;
  /** Fraction of total revenue (cost ratio), plus fixed component. */
  revShare: number;
  fixed: number;
  growth: number;
}

const COST_SPECS: CostSpec[] = [
  { line: "cogs_cloud", revShare: 0.14, fixed: 180_000, growth: 0.004 },
  { line: "cogs_support", revShare: 0.09, fixed: 120_000, growth: 0.003 },
  { line: "opex_sm", revShare: 0.22, fixed: 260_000, growth: 0.006 },
  { line: "opex_rd", revShare: 0.16, fixed: 340_000, growth: 0.005 },
  { line: "opex_ga", revShare: 0.08, fixed: 210_000, growth: 0.002 },
  { line: "da", revShare: 0.0, fixed: 260_000, growth: 0.004 },
];

const SCENARIO_COST_BIAS: Record<Scenario, number> = { AC: 1, BU: 0.98, FC: 0.995 };

function buildPnlFacts(): PnlFact[] {
  const facts: PnlFact[] = [];
  PERIODS.forEach((period, i) => {
    const actual = isActualPeriod(period);
    const scenarios: Scenario[] = actual ? ["AC", "BU", "FC"] : ["BU", "FC"];
    for (const scenario of scenarios) {
      for (const spec of PRODUCT_SPECS) {
        facts.push({ period, scenario, line: spec.line, value: revenueFor(period, scenario, spec.line) });
      }
      const rev = totalRevenue(period, scenario);
      for (const cost of COST_SPECS) {
        const variable = rev * cost.revShare;
        const fixed = cost.fixed * growth(i, cost.growth);
        const raw = (variable + fixed) * SCENARIO_COST_BIAS[scenario] * (scenario === "AC" ? jitter(0.02) : 1);
        facts.push({ period, scenario, line: cost.line, value: Math.round(raw) });
      }
    }
  });
  return facts;
}

export const pnlFacts: PnlFact[] = buildPnlFacts();

function buildWorkingCapital(): WorkingCapitalFact[] {
  return PERIODS.filter(isActualPeriod).map((period, i) => {
    const rev = totalRevenue(period, "AC");
    return {
      period,
      ar: Math.round(rev * 1.9 * jitter(0.04)),
      inventory: Math.round(rev * 0.35 * jitter(0.05)),
      ap: Math.round(rev * 0.8 * jitter(0.04)),
      capex: Math.round(220_000 * growth(i, 0.004) * jitter(0.08)),
    };
  });
}

export const wcFacts: WorkingCapitalFact[] = buildWorkingCapital();

const FX_BASE: Record<CurrencyCode, number> = { USD: 1, EUR: 0.92, GBP: 0.79 };

function buildFxRates(): FxRate[] {
  const out: FxRate[] = [];
  PERIODS.forEach((period, i) => {
    for (const currency of CURRENCIES) {
      const drift = 1 + Math.sin(i / 5) * 0.03;
      out.push({ period, currency, avgRate: +(FX_BASE[currency] * drift).toFixed(4) });
    }
  });
  return out;
}

export const fxRates: FxRate[] = buildFxRates();

/** Bundle for consumers that want one import. */
export const STATEMENTS = {
  calendar: CALENDAR,
  asOf: AS_OF,
  periods: PERIODS,
  pnlRows: PNL_ROWS,
  pnlLeaves: PNL_LEAVES,
  leafSign: LEAF_SIGN,
  pnlFacts,
  productFacts,
  wcFacts,
  fxRates,
  currencies: CURRENCIES,
  baseCurrency: BASE_CURRENCY,
} as const;
