import { useMemo } from 'react';

import { useI18n } from '@/i18n';
import type { ConditionModel, ScenarioId } from './conditionData';

export interface ConditionState {
  scenario: ScenarioId;
  year: number;
}

const SCENARIOS: ScenarioId[] = ['nichtstun', 'priorisiert', 'gleichverteilt'];

/** Zustandsnote colours, matching the shader in buildings.ts so panel and scene agree. */
const GRADE_COLOURS = ['#4d9e5c', '#9ebb52', '#e6bd47', '#de7838', '#c23d3d'];

/**
 * Money at the scale this lens deals in.
 *
 * ⚠️ Switches to billions above a thousand million, and that is not cosmetic. In German number
 * formatting the thousands separator is a dot, so a backlog of 8 466 million rendered as
 * "8.466 Mio. €" reads to most people as eight-point-four-six-six million — off by three orders of
 * magnitude, in the one figure a Kanzler would actually quote.
 */
function money(eur: number, locale: string): string {
  const tag = locale === 'de' ? 'de-DE' : 'en-GB';
  if (Math.abs(eur) >= 1e9) {
    return `${(eur / 1e9).toLocaleString(tag, { maximumFractionDigits: 2 })} ${
      locale === 'de' ? 'Mrd. €' : 'bn €'
    }`;
  }
  return `${(eur / 1e6).toLocaleString(tag, { maximumFractionDigits: 0 })} ${
    locale === 'de' ? 'Mio. €' : 'm €'
  }`;
}

/**
 * The Sanierungsstau lens.
 *
 * ⚠️ **The badge is not decoration and must not be made subtle.** Every figure on this panel is
 * generated by a seeded model in `tools/geodata/build_condition.py`; none of it describes the real
 * University of Tübingen, which publishes nothing of the kind. The one thing that would make this
 * app genuinely damaging is a screenshot of an invented renovation backlog against a named real
 * institution with no visible marking.
 *
 * The comparison is the point of the lens, and it is deliberately not a slogan. Spreading the
 * money renovates MORE BUILDINGS; prioritising protects more of the FLOOR AREA PEOPLE ARE IN. The
 * two measures cross over, and showing both is the difference between a model and a poster.
 */
export function ConditionPanel({
  model,
  state,
  onChange,
}: {
  model: ConditionModel;
  state: ConditionState;
  onChange: (next: ConditionState) => void;
}) {
  const { t, locale } = useI18n();

  const scenario = model.scenarios[state.scenario];
  const current = useMemo(
    () => scenario.curve.find((c) => c.year === state.year) ?? scenario.curve[0],
    [scenario, state.year]
  );

  const gradeMix = useMemo(() => {
    const counts = [0, 0, 0, 0, 0];
    const renovated = scenario.renovatedYear;
    model.grade.forEach((g, i) => {
      const done = renovated[i] > 0 && state.year >= renovated[i];
      counts[(done ? 1 : g) - 1] += 1;
    });
    return counts;
  }, [model.grade, scenario.renovatedYear, state.year]);

  const total = model.buildingCount;
  const peak = Math.max(...SCENARIOS.map((s) => model.scenarios[s].curve[0].backlogEur));

  return (
    <section className="mt-4" data-testid="condition-panel">
      <div
        data-testid="synthetic-badge"
        className="rounded border border-amber-500/70 bg-amber-500/10 p-2.5 text-[0.68rem] leading-relaxed text-amber-200"
      >
        <p className="font-semibold uppercase tracking-[0.14em]">{t('condition.syntheticTitle')}</p>
        <p className="mt-1 text-amber-100/80">{t('condition.syntheticBody')}</p>
      </div>

      <h3 className="mt-4 text-xs uppercase tracking-[0.18em] text-stone-400">
        {t('condition.scenario')}
      </h3>
      <div className="mt-2 grid grid-cols-3 gap-1">
        {SCENARIOS.map((id) => (
          <button
            key={id}
            type="button"
            data-testid={`scenario-${id}`}
            onClick={() => onChange({ ...state, scenario: id })}
            className={`rounded px-2 py-1.5 text-[0.68rem] transition ${
              id === state.scenario
                ? 'bg-stone-100 text-stone-900'
                : 'bg-stone-800 text-stone-300 hover:bg-stone-700'
            }`}
          >
            {t(`condition.scenarios.${id}`)}
          </button>
        ))}
      </div>

      <div className="mt-4 flex items-baseline justify-between">
        <h3 className="text-xs uppercase tracking-[0.18em] text-stone-400">
          {t('condition.year')}
        </h3>
        <span data-testid="condition-year" className="font-mono text-sm text-stone-100">
          {state.year}
        </span>
      </div>
      <input
        type="range"
        data-testid="condition-year-slider"
        min={model.years[0]}
        max={model.years[model.years.length - 1]}
        value={state.year}
        onChange={(e) => onChange({ ...state, year: Number(e.target.value) })}
        className="mt-2 w-full accent-amber-400"
      />

      <dl className="mt-4 space-y-1 text-xs">
        <div className="flex justify-between gap-2">
          <dt className="text-stone-400">{t('condition.backlog')}</dt>
          <dd data-testid="condition-backlog" className="font-medium tabular-nums">
            {money(current.backlogEur, locale)}
          </dd>
        </div>
        <div className="flex justify-between gap-2">
          <dt className="text-stone-400">{t('condition.spent')}</dt>
          <dd className="font-medium tabular-nums">{money(current.cumulativeEur, locale)}</dd>
        </div>
        <div className="flex justify-between gap-2">
          <dt className="text-stone-400">{t('condition.renovated')}</dt>
          <dd className="font-medium tabular-nums">
            {current.renovated} / {total}
          </dd>
        </div>
        <div className="flex justify-between gap-2">
          <dt className="text-stone-400">{t('condition.sharePoor')}</dt>
          <dd className="font-medium tabular-nums">{(current.sharePoor * 100).toFixed(1)} %</dd>
        </div>
        <div className="flex justify-between gap-2">
          <dt className="text-stone-400">{t('condition.poorWeighted')}</dt>
          <dd data-testid="condition-poor-weighted" className="font-medium tabular-nums">
            {(current.poorWeighted * 100).toFixed(1)} %
          </dd>
        </div>
      </dl>

      {/* Grade mix as a stacked bar — the fastest read of "is the estate getting better". */}
      <h3 className="mt-4 text-xs uppercase tracking-[0.18em] text-stone-400">
        {t('condition.gradeMix')}
      </h3>
      <div className="mt-2 flex h-4 overflow-hidden rounded">
        {gradeMix.map((n, i) => (
          <div
            key={i}
            style={{ width: `${(n / total) * 100}%`, background: GRADE_COLOURS[i] }}
            title={`${t('condition.grade')} ${i + 1}: ${n}`}
          />
        ))}
      </div>
      <div className="mt-1 flex justify-between text-[0.6rem] text-stone-500">
        <span>{t('condition.gradeGood')}</span>
        <span>{t('condition.gradeBad')}</span>
      </div>

      {/* Backlog curves, all three at once. A scenario compared only against itself proves nothing. */}
      <h3 className="mt-4 text-xs uppercase tracking-[0.18em] text-stone-400">
        {t('condition.curve')}
      </h3>
      <svg viewBox="0 0 240 90" className="mt-2 w-full" role="img" aria-label={t('condition.curve')}>
        {SCENARIOS.map((id, s) => {
          const curve = model.scenarios[id].curve;
          const points = curve
            .map((c, i) => {
              const x = (i / (curve.length - 1)) * 236 + 2;
              const y = 86 - (c.backlogEur / peak) * 70;
              return `${x.toFixed(1)},${y.toFixed(1)}`;
            })
            .join(' ');
          const active = id === state.scenario;
          return (
            <polyline
              key={id}
              points={points}
              fill="none"
              stroke={['#c23d3d', '#4d9e5c', '#6f9fd8'][s]}
              strokeWidth={active ? 2.2 : 1}
              opacity={active ? 1 : 0.45}
            />
          );
        })}
        <line
          x1={((state.year - model.years[0]) / (model.years.length - 1)) * 236 + 2}
          y1={2}
          x2={((state.year - model.years[0]) / (model.years.length - 1)) * 236 + 2}
          y2={86}
          stroke="#e7e5e4"
          strokeWidth={0.6}
          opacity={0.5}
        />
      </svg>

      <p className="mt-3 text-[0.65rem] leading-relaxed text-stone-500">
        {t('condition.crossover')}
      </p>
      <p className="mt-2 text-[0.65rem] leading-relaxed text-stone-500">
        {t('condition.provenance', {
          seed: String(model.seed),
          budget: money(model.annualBudgetEur, locale),
        })}
      </p>
    </section>
  );
}
